USE [MASTER]
GO
DROP LOGIN [LOGINGIROSRPT]
GO
USE [MASTER]
GO
CREATE LOGIN [LOGINGIROSRPT] WITH PASSWORD=N'RPT0P4SSW0RD!.', 
DEFAULT_DATABASE=[MASTER], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Autorizador]
CREATE USER [LOGINGIROSRPT] FOR LOGIN [LOGINGIROSRPT]
GO

GRANT EXECUTE ON OBJECT::PRC_Tbl_TransaccionGF_Reporte_Avances_Rever TO [LOGINGIROSRPT];
GRANT EXECUTE ON OBJECT::PRC_Tbl_TransaccionGF_Reporte_Transacc_Rechazadas TO [LOGINGIROSRPT];
GRANT EXECUTE ON OBJECT::PRC_Tbl_TransaccionGF_Select_Reporte_Transa_Apro TO [LOGINGIROSRPT];

---------------
USE  [58Bonita]

GRANT EXECUTE ON OBJECT::BonSPTBL_ARCHIVO_TARJETA_SelectValidarConsecutivo TO [LOGINGIROS];

--------------------------------------------------------------------
--------------------------------------------------------------------
USE [MASTER]
GO
DROP LOGIN [LOGINGIROS]
GO
USE [MASTER]
GO
CREATE LOGIN [LOGINGIROS] WITH PASSWORD=N'P4SSW0RD!.', 
DEFAULT_DATABASE=[MASTER], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Autorizador]
GO
CREATE USER [LOGINGIROS] FOR LOGIN [LOGINGIROS]
GO

------------------OBJETOS-------
USE  [AUTORIZADOR]
GO
GRANT EXECUTE ON OBJECT::PRC_TBL_LOGAPLICACION_INSERT TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::Update_TransaccionGF TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::REVERSO_VALOR_GF TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::Select_NombreRespuestaGF TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::Insert_Respuesta_GF TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::PRC_TBL_MOTIVOGF_SELECT TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::TRXACTULIZARAUTORIZADOR_GF TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::PRCSOLICITARFINANCIACIONONLINE_GF TO [LOGINGIROS];
GRANT EXECUTE ON OBJECT::PRC_Tbl_DatosOpenCardGF_Insert TO [LOGINGIROS];

USE [MASTER]
GO
DROP LOGIN [LOGINGIROSEWINSRV]
GO
USE [MASTER]
GO
CREATE LOGIN [LOGINGIROSEWINSRV] WITH PASSWORD=N'P4SSW0RD!.', 
DEFAULT_DATABASE=[MASTER], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Autorizador]
GO
--CREATE USER [LOGINGIROSEWINSRV] FOR LOGIN [LOGINGIROSEWINSRV]
GO

GRANT EXECUTE ON OBJECT::PRC_TBL_LOGAPLICACION_INSERT TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_ARH9TXT_COMISIONAVANCE_GF   TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_ARH9TXT_AVANCES  TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_TBL_CheckListArchivoGF_Select  TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_Tbl_CheckListArchivoGF_Insert  TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_TBL_TRANSACCIONGF_SELECT_PENDIENTESARCHI9_COMISIONES  TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_TBL_TRANSACCIONGF_UPDATE_PENDIENTESARCHI9_COMISIONES  TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_TBL_TRANSACCIONGF_UPDATE_PENDIENTESARCHI9_AVANCES  TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_TBL_TRANSACCIONGF_SELECT_PENDIENTESARCHI9_AVANCES  TO [LOGINGIROSEWINSRV];
GRANT EXECUTE ON OBJECT::PRC_TBL_CheckListArchivoGF_Update  TO [LOGINGIROSEWINSRV];

--GRANT SELECT ON OBJECT::Tbl_LogAplicacion
--GRANT SELECT ON OBJECT::Tbl_tmpArch9GF
GRANT SELECT ON OBJECT::TBL_TMPARCH9 TO [LOGINGIROSEWINSRV];
GRANT DELETE ON OBJECT::TBL_TMPARCH9 TO [LOGINGIROSEWINSRV];
GRANT INSERT ON OBJECT::TBL_TMPARCH9 TO [LOGINGIROSEWINSRV];
GRANT SELECT ON OBJECT::Tbl_CheckListArchivoGF TO [LOGINGIROSEWINSRV];
GRANT UPDATE ON OBJECT::Tbl_CheckListArchivoGF TO [LOGINGIROSEWINSRV];

--GRANT EXECUTE ON OBJECT::TBL_TMPARCH9 TO [LOGINGIROSEWINSRV];

--GRANT SELECT ON OBJECT::Tbl_CheckListArchivoGF 
--GRANT SELECT ON OBJECT::Tbl_TransaccionGF

--GRANT SELECT ON OBJECT::VST_TRXCARGAR_COMISIONES_GF
--GRANT SELECT ON OBJECT::VST_TRXCARGAR_AVANCES




USE [CreditosProd]
GO
CREATE USER [LOGINGIROS] FOR LOGIN [LOGINGIROS]
GO

------------------OBJETOS-------
GRANT EXECUTE ON OBJECT::PRC_TBL_ITEMCONFIG_VALORES_GF TO [LOGINGIROS];
GRANT REVOKE ON OBJECT::TBL_ITEMCONFIG TO [LOGINGIROS];




------------------OBJETOS-------
USE [CreditosProd]
GO
CREATE USER [LOGINGIROSEWINSRV] FOR LOGIN [LOGINGIROSEWINSRV]
GO

------------------OBJETOS-------
GRANT EXECUTE ON OBJECT::PRC_TBL_ITEMCONFIG_VALORES_GF TO [LOGINGIROSEWINSRV];
GRANT REVOKE ON OBJECT::TBL_ITEMCONFIG TO [LOGINGIROSEWINSRV];







