USE [CreditosProd]
GO
GRANT EXECUTE ON OBJECT::PRCITEMCONFIG  TO LOGINTIGO;
GRANT EXECUTE ON OBJECT::PCSTslSolicitudCredito_Insert  TO LOGINTIGO;
--GRANT EXECUTE ON OBJECT::PCSTslSolicitudCredito__I  TO LOGINTIGO;
GRANT EXECUTE ON OBJECT::PCS_TBL_ARCHIVOADJUNTOCredito_Insert  TO LOGINTIGO;
USE  [AUTORIZADOR]
GO
GRANT EXECUTE ON OBJECT::Autorizador_SelectEstados  TO LOGINTIGO;
GRANT EXECUTE ON OBJECT::SAIPBuscarSolicitud  TO LOGINTIGO;
GRANT EXECUTE ON OBJECT::SAIPGetEstadosMontoPreAprobado  TO LOGINTIGO;
GRANT EXECUTE ON OBJECT::SAIP_ConsultaEstadoTigo  TO LOGINTIGO;
GRANT EXECUTE ON OBJECT::SAIPInsertMontoPreAprobado  TO LOGINTIGO; 
---Select 
GRANT SELECT  ON OBJECT::Tbl_Estado_Tigo TO LOGINTIGO;
GRANT SELECT  ON OBJECT::Tbl_CausalEstadoTigo TO LOGINTIGO;
GRANT SELECT  ON OBJECT::Tbl_Solicitud  TO LOGINTIGO;
GRANT SELECT  ON OBJECT::VST_ESTADOSTIGO TO LOGINTIGO;