USE [MASTER]
GO
DROP LOGIN [LOGINEFECTYWINSRV]
GO
USE [MASTER]
GO
CREATE LOGIN [LOGINEFECTYWINSRV] WITH PASSWORD=N'P4SSW0RD!.', 
DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [Autorizador]
GO
CREATE USER [LOGINEFECTYWINSRV] FOR LOGIN [LOGINEFECTYWINSRV]
GO
USE [CreditosProd]
GO
CREATE USER [LOGINEFECTYWINSRV] FOR LOGIN [LOGINEFECTYWINSRV]
GO

GO

------------------OBJETOS-------
USE  [AUTORIZADOR]
GO
GRANT EXECUTE ON OBJECT::ACTUALIZAR_TRANSACCIONES_AVANCE TO [LOGINEFECTYWINSRV];
GRANT EXECUTE ON OBJECT::PRC_ARH9TXT_AVANCES_EFECTY TO [LOGINEFECTYWINSRV];
GRANT EXECUTE ON OBJECT::PRC_ARH9TXT_COMISIONAVANCE TO [LOGINEFECTYWINSRV];
GRANT EXECUTE ON OBJECT::TRANSACCIONES_X_ACTUALIZAR_AVANCES TO [LOGINEFECTYWINSRV];

USE [CREDITOSPROD]
GO
GRANT EXECUTE ON OBJECT::SP_SELECT_COMISION TO [LOGINEFECTYWINSRV];

USE [MASTER]
GO
ALTER LOGIN [LOGINEFECTY] WITH PASSWORD=N'P4SSW0RD!.'
GO

USE  [AUTORIZADOR]
go
--Revoke EXECUTE ON OBJECT::PRC_ARH9TXT_AVANCES TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::TRX_ACTULIZAR_AUTORIZADOR_EFECTY TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_ARH9TXT_AVANCES TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_ARH9TXT_AVANCES_EFECTY TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_ARH9TXT_COMISIONAVANCE TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::INSLOG TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::TRANSACCIONES_X_ACTUALIZAR_AVANCES  TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::TRX_ACTULIZAR_AUTORIZADOR_EFECTY  TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::TRANSACCIONES_X_ACTUALIZAR_AVANCES TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::TRX_ACTULIZAR_AUTORIZADOR_EFECTY TO LOGINEFECTY;
GRANT SELECT  ON OBJECT::VST_TRXCARGAR_AVANCES TO LOGINEFECTY;
GRANT SELECT  ON OBJECT::VST_TRXCARGAR_AVANCES_EFECTY TO LOGINEFECTY;
GRANT SELECT  ON OBJECT::TBL_LOGACCion TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::SELECT_RESPUESTAS_EFECTY  TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::INSLOG   TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::SELECT_RESPUESTAS_EFECTY   TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::INSERT_RESPUESTAS_EFECTY   TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_RECHAZARTRANSACCION_EFECTY   TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_SELECT_SALDOS_EFECTY   TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_SOLICITARFINANCIACION_EFECTY   TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_REGISTRAR_TRANSACCIONES_EFECTY   TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::PRC_RESERVARTRANSACCION_EFECTY  TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::Update_Transaccion_EFECTY  TO LOGINEFECTY;
GRANT EXECUTE ON OBJECT::REVERSO_VALOR_EFECTY  TO LOGINEFECTY;
USE [CreditosProd]
GO
GRANT EXECUTE ON OBJECT::SELECT_MONTOS_EFECTY TO loginEfecty;
GRANT EXECUTE ON OBJECT::SP_SELECT_COMISION TO loginEfecty;



USE  [AUTORIZADOR]
go
SELECT * FROM sys.database_permissions AS dp 
    JOIN sys.system_objects AS so
    ON dp.major_id = so.object_id
    WHERE dp.class = 1 AND so.parent_object_id = 0 ;
    USE  [AUTORIZADOR]
go
SELECT * FROM fn_my_permissions(NULL, '[DATABASE]');









----Objetos  Reportes--------------
USE [MASTER]
GO
CREATE LOGIN [LOGINEFECTYRPT] WITH PASSWORD=N'P4SSW0RD!.', 
DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

GO
USE [Autorizador]
GO
CREATE USER [LOGINEFECTYRPT] FOR LOGIN [LOGINEFECTYRPT]
GO
USE [CreditosProd]
GO
CREATE USER [LOGINEFECTYRPT] FOR LOGIN [LOGINEFECTYRPT]
GO

---PERMISOS
USE [Autorizador]
GO
GRANT EXECUTE ON OBJECT:: SP_REP_LOGAUTORIZADOR TO [LOGINEFECTYRPT];
GRANT EXECUTE ON OBJECT:: SP_REP_SALDOSAUTORIZADOR TO [LOGINEFECTYRPT];
GRANT EXECUTE ON OBJECT:: SP_REP_TRANSACCIONESEFECTY TO [LOGINEFECTYRPT];
