-------------------------------------------------------------
DECLARE  @TABLA VARCHAR(50)
SET @TABLA='ARCHIVO_TARJETA'
SELECT 'INSERT INTO [DBO].[' +@TABLA +'] (' AS T
UNION ALL
SELECT
 SC.NAME  + ',' AS T--,
--SC.NAME AS COLUMNA,
--ST.NAME AS TIPO,
--SC.MAX_LENGTH AS TAMAÑO
FROM SYS.OBJECTS SO INNER JOIN SYS.COLUMNS SC ON
SO.OBJECT_ID = SC.OBJECT_ID INNER JOIN
SYS.TYPES ST ON ST.SYSTEM_TYPE_ID = SC.SYSTEM_TYPE_ID AND
ST.NAME != 'SYSNAME' WHERE SO.TYPE = 'U' AND SO.NAME=@TABLA
-------------------------------------------------------------
DECLARE  @TABLA VARCHAR(50)
SET @TABLA='ARCHIVO_TARJETA'
--SELECT CONVERT(
SELECT
 SC.NAME  + ',' AS T,
'ClMN01' AS COLUMNA,
'CONVERT(' + CONVERT(VARCHAR(50),ST.NAME) + ',' + ')',
ST.NAME AS TIPO,
SC.MAX_LENGTH AS TAMAÑO
FROM SYS.OBJECTS SO INNER JOIN SYS.COLUMNS SC ON
SO.OBJECT_ID = SC.OBJECT_ID INNER JOIN
SYS.TYPES ST ON ST.SYSTEM_TYPE_ID = SC.SYSTEM_TYPE_ID AND
ST.NAME != 'SYSNAME' WHERE SO.TYPE = 'U' AND SO.NAME=@TABLA


DECLARE  @TABLA VARCHAR(50)
SET @TABLA='ARCHIVO_TARJETA'
--SELECT CONVERT(

DECLARE vend_cursor CURSOR
    FOR SELECT
 SC.NAME  + ',' AS T,
'ClMN01' AS COLUMNA,
'CONVERT(' + CONVERT(VARCHAR(50),ST.NAME) + ',' + ')',
ST.NAME AS TIPO,
SC.MAX_LENGTH AS TAMAÑO
FROM SYS.OBJECTS SO INNER JOIN SYS.COLUMNS SC ON
SO.OBJECT_ID = SC.OBJECT_ID INNER JOIN
SYS.TYPES ST ON ST.SYSTEM_TYPE_ID = SC.SYSTEM_TYPE_ID AND
ST.NAME != 'SYSNAME' WHERE SO.TYPE = 'U' AND SO.NAME=@TABLA
OPEN vend_cursor
FETCH NEXT FROM vend_cursor;